apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Release.Name }}.wesaynow.com"
  gateways:
  - {{ .Release.Name }}
  http:
  - route:
    - destination:
        host: {{ include "deployment.fullname" . }}
        port:
          number: {{ .Values.service.port }}
